module.exports = {
    CHIRP = 'CHIRP',
    CHIRPED = 'CHIRPED',
    GOTCHIRPS ='GOTCHIRPS',
    GOT_CURRENT_USER = 'GOT_CURRENT_USER',
    GOT_USERS = 'GOT_USERS',
    FOLLOW = 'FOLLOW',
    UNFOLLOW = 'UNFOLLOW',
    FOLLOWED = 'FOLLOWED',
    UNFOLLOWED = 'UNFOLLOWED'
};